export type TLamp = {
    id: string,
    title: string,
    designation?: string[],
    imgUrl?: string[],
    ip?: string,
    climate?: string[],
    type?: string,
    purpose?: string,
    warranty?: number,
    material?: string,
    color?: string,
    powerRange?: number[],
    lens?: string[],
}
