import imgFL60_01 from '../../assets/images/product/lamps/fl-60-01.jpg';
import imgFL60_02 from '../../assets/images/product/lamps/fl-60-02.jpg';
import imgFL60_03 from '../../assets/images/product/lamps/fl-60-03.jpg';
import imgFL60D_01 from '../../assets/images/product/lamps/fl-60-design-01.jpg';
import imgFL60D_02 from '../../assets/images/product/lamps/fl-60-design-02.jpg';
import imgFG120_01 from '../../assets/images/product/lamps/fg-120-220-01.jpg';
import imgFG120_02 from '../../assets/images/product/lamps/fg-120-220-02.jpg';
import imgFG120_03 from '../../assets/images/product/lamps/fg-120-150-01.jpg';
import imgFG120_04 from '../../assets/images/product/lamps/fg-120-150-02.jpg';
import imgFG120_05 from '../../assets/images/product/lamps/fg-120-100-01.jpg';
import imgFG120_06 from '../../assets/images/product/lamps/fg-120-100-02.jpg';

export type TLamp = {
    id: string,
    title: string,
    designation?: string[],
    imgUrl?: string[],
    ip?: string,
    climate?: string[],
    type?: string,
    purpose?: string,
    warranty?: number,
    material?: string,
    color?: string,
    powerRange?: number[],
    lens?: string[],
}

export const lamps: TLamp[] = [{
    id: "lamp001",
    title: "FL 60",
    designation: ["KOP052"],
    imgUrl: [imgFL60_01, imgFL60_02, imgFL60_03],
    ip: "IP20",
    climate: ["УХЛ3.1"],
    type: "линейный",
    purpose: "комерческое освещение",
    warranty: 5,
    material: "алюминиевый корпус",
    color: "серый",
    powerRange: [17, 34],
    lens: [
        "микропризма (PRISM)",
        "опал (OPAL)",
        "прозрачный (CRYSTAL)",
        "фрозен (ICE)",
    ],
},
{
    id: "lamp002",
    title: "FL 60 DESIGN",
    designation: ["KOP111"],
    imgUrl: [imgFL60D_01, imgFL60D_02, imgFL60_01, imgFL60_02, imgFL60_03],
    ip: "IP20",
    climate: ["УХЛ3.1"],
    type: "линейный",
    purpose: "комерческое освещение",
    warranty: 5,
    material: "алюминиевый корпус",
    color: "серый",
    powerRange: [17, 52],
    lens: [
        "микропризма (PRISM)",
        "опал (OPAL)",
        "прозрачный (CRYSTAL)",
    ],
},
{
    id: "lamp003",
    title: "FG 50",
    designation: ["KOP017", "KOP093"],
    imgUrl: ["/"],
    ip: "IP65",
    climate: ["УХЛ2", "УХЛ3.1"],
    type: "линейный",
    purpose: "промышленное освещение",
    warranty: 5,
    material: "алюминиевый корпус",
    color: "серый",
    powerRange: [20, 112],
    lens: [
        "опал (OPAL)",
        "прозрачный (CRYSTAL)",
        "линзы рассеивания",
    ],
},
{
    id: "lamp004",
    title: "FG 55",
    designation: ["KOP053"],
    imgUrl: ["/"],
    ip: "IP65",
    climate: ["УХЛ2", "УХЛ3.1"],
    type: "линейный",
    purpose: "промышленное освещение",
    warranty: 5,
    material: "алюминиевый корпус",
    color: "серый",
    powerRange: [11, 112],
    lens: [
        "опал (OPAL)",
        "прозрачный (CRYSTAL)",
    ],
},
{
    id: "lamp005",
    title: "FG 120",
    designation: ["KOP082"],
    imgUrl: [imgFG120_01, imgFG120_02, imgFG120_03, imgFG120_04, imgFG120_05, imgFG120_06],
    ip: "IP65",
    climate: ["УХЛ2", ],
    type: "подвесной",
    purpose: "промышленное освещение",
    warranty: 7,
    material: "алюминий, сталь",
    color: "черный",
    powerRange: [100, 220],
    lens: [
        "линзы рассеивания",
    ],
},
{
    id: "lamp006",
    title: "FT 185",
    designation: ["KOP149"],
    imgUrl: ["/"],
    ip: "IP40",
    climate: ["УХЛ2", ],
    type: "трековый",
    purpose: "комерческое освещение",
    warranty: 5,
    material: "сталь",
    color: "серый",
    powerRange: [47, 62],
    lens: [
        "линзы рассеивания",
    ],
},
{
    id: "lamp007",
    title: "FT 85",
    designation: ["KOP085"],
    imgUrl: ["/"],
    ip: "IP20",
    climate: ["УХЛ4", ],
    type: "трековый",
    purpose: "комерческое освещение",
    warranty: 5,
    material: "алюминиевый корпус",
    color: "белый",
    powerRange: [30, 40],
    lens: [
        "отражатель",
    ],
},
];